require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe FirmwaresController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Firmware. As you add validations to Firmware, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
     filename: "example.bin",
     content_type: "application/binary",
     file_content: "<\x7F\x00 5\x04\"\x00I\x04\"\x00M\x04\"\x00Q\x04\"\x00Q\x04\"\x00Q\x04\"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00Q\x04\"\x00Q\x04\"",
     checksum: Digest::SHA1.hexdigest("<\x7F\x00 5\x04\"\x00I\x04\"\x00M\x04\"\x00Q\x04\"\x00Q\x04\"\x00Q\x04\"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00Q\x04\"\x00Q\x04\"")
    }
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FirmwaresController. Be sure to keep this updated too.
 let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all firmwares as @firmwares" do
      firmware = Firmware.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:firmwares)).to eq([firmware])
    end
  end

  describe "GET #show" do
    it "assigns the requested firmware as @firmware" do
      firmware = Firmware.create! valid_attributes
      get :show, {:id => firmware.to_param}, valid_session
      expect(assigns(:firmware)).to eq(firmware)
    end
  end

  describe "GET #new" do
    it "assigns a new firmware as @firmware" do
      get :new, {}, valid_session
      expect(assigns(:firmware)).to be_a_new(Firmware)
    end
  end

  describe "GET #edit" do
    it "assigns the requested firmware as @firmware" do
      firmware = Firmware.create! valid_attributes
      get :edit, {:id => firmware.to_param}, valid_session
      expect(assigns(:firmware)).to eq(firmware)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Firmware" do
        expect {
          post :create, {:firmware => valid_attributes}, valid_session
        }.to change(Firmware, :count).by(1)
      end

      it "assigns a newly created firmware as @firmware" do
        post :create, {:firmware => valid_attributes}, valid_session
        expect(assigns(:firmware)).to be_a(Firmware)
        expect(assigns(:firmware)).to be_persisted
      end

      it "redirects to the created firmware" do
        post :create, {:firmware => valid_attributes}, valid_session
        expect(response).to redirect_to(Firmware.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved firmware as @firmware" do
        post :create, {:firmware => invalid_attributes}, valid_session
        expect(assigns(:firmware)).to be_a_new(Firmware)
      end

      it "re-renders the 'new' template" do
        post :create, {:firmware => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested firmware" do
        firmware = Firmware.create! valid_attributes
        put :update, {:id => firmware.to_param, :firmware => new_attributes}, valid_session
        firmware.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested firmware as @firmware" do
        firmware = Firmware.create! valid_attributes
        put :update, {:id => firmware.to_param, :firmware => valid_attributes}, valid_session
        expect(assigns(:firmware)).to eq(firmware)
      end

      it "redirects to the firmware" do
        firmware = Firmware.create! valid_attributes
        put :update, {:id => firmware.to_param, :firmware => valid_attributes}, valid_session
        expect(response).to redirect_to(firmware)
      end
    end

    context "with invalid params" do
      it "assigns the firmware as @firmware" do
        firmware = Firmware.create! valid_attributes
        put :update, {:id => firmware.to_param, :firmware => invalid_attributes}, valid_session
        expect(assigns(:firmware)).to eq(firmware)
      end

      it "re-renders the 'edit' template" do
        firmware = Firmware.create! valid_attributes
        put :update, {:id => firmware.to_param, :firmware => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested firmware" do
      firmware = Firmware.create! valid_attributes
      expect {
        delete :destroy, {:id => firmware.to_param}, valid_session
      }.to change(Firmware, :count).by(-1)
    end

    it "redirects to the firmwares list" do
      firmware = Firmware.create! valid_attributes
      delete :destroy, {:id => firmware.to_param}, valid_session
      expect(response).to redirect_to(firmwares_url)
    end
  end

end
