require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe LampStatsController, type: :controller do

  before :all do
    @authorized_user = auth_user(ability: :can_all, resource: 'Lamp')
  end
  before :each do
    sign_in @authorized_user
  end

  # This should return the minimal set of attributes required to create a valid
  # LampStat. As you add validations to LampStat, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
     :serial_num=>123,
     :date=>DateTime.now,
     :pwr=>31,
     :current=>0.0,
     :volts=>0.0,
     :tCom=>28.6,
     :tLed1=>26.7,
     :tLed2=>26.9,
     :sLum=>330,
     :rssiDev=>-37,
     :lqiDev=>141,
     :correlationDev=>107,
     :rssi=>-36,
     :lqi=>144,
     :correlation=>108,
     :sentPkts=>819,
     :rcvPkts=>816,
     :lastReboot=>3119,
     :txPwr=>7,
     :ctrlRestart=>32784,
     :vFirmware=>7,
     :vCmd=>7,
     :cksCfg=>2819,
     :appCksErr=>0,
     :cmdNotImp=>0,
     :online=>false,
     :communicating=>true,
     :sunrise=>"7:06",
     :sunset=>"17:43",
     :alerts=>0,
     :errorsDev=>0
    }
  }

  let(:invalid_attributes) {
    {serial_num: nil}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LampStatsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all lamp_stats as @lamp_stats" do
      lamp_stat = LampStat.create! valid_attributes
      lamp = FactoryGirl.create(:lamp)
      get :index, {lamp_id: lamp.id }, valid_session
      expect(assigns(:chart)).to eq([lamp_stat])
    end
  end

  describe "GET #show" do
    it "assigns the requested lamp_stat as @lamp_stat" do
      lamp_stat = LampStat.create! valid_attributes
      get :show, {:id => lamp_stat.to_param}, valid_session
      expect(assigns(:lamp_stat)).to eq(lamp_stat)
    end
  end

  # describe "GET #new" do
  #   it "assigns a new lamp_stat as @lamp_stat" do
  #     get :new, {}, valid_session
  #     expect(assigns(:lamp_stat)).to be_a_new(LampStat)
  #   end
  # end

  # describe "GET #edit" do
  #   it "assigns the requested lamp_stat as @lamp_stat" do
  #     lamp_stat = LampStat.create! valid_attributes
  #     get :edit, {:id => lamp_stat.to_param}, valid_session
  #     expect(assigns(:lamp_stat)).to eq(lamp_stat)
  #   end
  # end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new LampStat" do
        expect {
          post :create, {:lamp_stat => valid_attributes}, valid_session
        }.to change(LampStat, :count).by(1)
      end

      it "assigns a newly created lamp_stat as @lamp_stat" do
        product = FactoryGirl.create(:product, serial_number: 123)
        task = FactoryGirl.create(:task, node: product.node, company: product.company)
        post :create, {:lamp_stat => valid_attributes}, valid_session
        expect(assigns(:lamp_stat)).to be_a(LampStat)
        expect(assigns(:lamp_stat)).to be_persisted
        expect(assigns(:tasks)).to be_a(Hash)
        expect(assigns(:tasks)["id"]).to eq(task.id)
      end

      # it "redirects to the created lamp_stat" do
      #   post :create, {:lamp_stat => valid_attributes}, valid_session
      #   expect(response).to redirect_to(LampStat.last)
      # end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved lamp_stat as @lamp_stat" do
        post :create, {:lamp_stat => invalid_attributes}, valid_session
        expect(assigns(:lamp_stat)).to be_a_new(LampStat)
      end

      # it "re-renders the 'new' template" do
      #   post :create, {:lamp_stat => invalid_attributes}, valid_session
      #   expect(response).to render_template("new")
      # end
    end
  end

  # describe "PUT #update" do
  #   context "with valid params" do
  #     let(:new_attributes) {
  #       skip("Add a hash of attributes valid for your model")
  #     }
  #
  #     it "updates the requested lamp_stat" do
  #       lamp_stat = LampStat.create! valid_attributes
  #       put :update, {:id => lamp_stat.to_param, :lamp_stat => new_attributes}, valid_session
  #       lamp_stat.reload
  #       skip("Add assertions for updated state")
  #     end
  #
  #     it "assigns the requested lamp_stat as @lamp_stat" do
  #       lamp_stat = LampStat.create! valid_attributes
  #       put :update, {:id => lamp_stat.to_param, :lamp_stat => valid_attributes}, valid_session
  #       expect(assigns(:lamp_stat)).to eq(lamp_stat)
  #     end
  #
  #     it "redirects to the lamp_stat" do
  #       lamp_stat = LampStat.create! valid_attributes
  #       put :update, {:id => lamp_stat.to_param, :lamp_stat => valid_attributes}, valid_session
  #       expect(response).to redirect_to(lamp_stat)
  #     end
  #   end
  #
  #   context "with invalid params" do
  #     it "assigns the lamp_stat as @lamp_stat" do
  #       lamp_stat = LampStat.create! valid_attributes
  #       put :update, {:id => lamp_stat.to_param, :lamp_stat => invalid_attributes}, valid_session
  #       expect(assigns(:lamp_stat)).to eq(lamp_stat)
  #     end
  #
  #     it "re-renders the 'edit' template" do
  #       lamp_stat = LampStat.create! valid_attributes
  #       put :update, {:id => lamp_stat.to_param, :lamp_stat => invalid_attributes}, valid_session
  #       expect(response).to render_template("edit")
  #     end
  #   end
  # end

  # describe "DELETE #destroy" do
  #   it "destroys the requested lamp_stat" do
  #     lamp_stat = LampStat.create! valid_attributes
  #     expect {
  #       delete :destroy, {:id => lamp_stat.to_param}, valid_session
  #     }.to change(LampStat, :count).by(-1)
  #   end
  #
  #   it "redirects to the lamp_stats list" do
  #     lamp_stat = LampStat.create! valid_attributes
  #     delete :destroy, {:id => lamp_stat.to_param}, valid_session
  #     expect(response).to redirect_to(lamp_stats_url)
  #   end
  # end

end
